App\Entity\CompanyPlace:
    exclusion_policy: ALL
    properties:
        identifier:
            expose: true
        description:
            expose: true
        markers:
            expose: true
