App\Topnode\BaseBundle\Entity\MappedSuperclass\State:
    exclusion_policy: ALL
    properties:
        identifier:
            expose: true
        code:
            expose: true
        initials:
            expose: true
        name:
            expose: true
