App\Topnode\BaseBundle\Entity\MappedSuperclass\City:
    exclusion_policy: ALL
    properties:
        identifier:
            expose: true
        code:
            expose: true
        name:
            expose: true
        state:
            expose: true
